### ISSUE TITLE
Parse error: ReferenceError: Can't find variable: $

### ISSUE THREAD

**Issue by kulisu** [nVisium/xssValidator#15]
got an error message while testing `resource-load.php` file.
phantomjs and casperjs both are throw the same error, maybe it's `evaluate()` problem ?

REF:
- [CasperJS Can't find variable $](http://stackoverflow.com/questions/15981450/casperjs-cant-find-variable)

---

test file: `resource-load.php`
error message: `Parse error: ReferenceError: Can't find variable: $`

BurpSuite version: [1.6.12](http://releases.portswigger.net/2015/03/v1612.html)
xssValidator version: [1.3.1](https://github.com/nVisium/xssValidator/releases/tag/1.3.1)

PhantomJS version: [1.9.8 x64](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2)
CasperJS version: [1.1-beta3](https://codeload.github.com/n1k0/casperjs/legacy.zip/1.1-beta3)

``` bash
phantomjs --debug=false --ignore-ssl-errors=true --load-images=true --local-to-remote-url-access=true --web-security=false --ssl-protocol=any xss.js &
```

---

Console Output

Received request with method type: POST
Processing Post Request
Beginning to parse page
    URL: http://192.168.30.56/resource-load.php?name=confirm(299792458)%3b
    Headers: GET /resource-load.php?name=confirm(299792458)%3b HTTP/1.1
Host: 192.168.30.56
Proxy-Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-TW,zh;q=0.8,en;q=0.6,zh-CN;q=0.4
Connection: close

Parse error: SyntaxError: Parse error
**Parse error: ReferenceError: Can't find variable: $**

---

Detailed Debug

2015-03-15T22:40:02 [DEBUG] WebpageCallbacks - getJsConfirmCallback
2015-03-15T22:40:02 [DEBUG] WebpageCallbacks - getJsConfirmCallback
2015-03-15T22:40:02 [DEBUG] WebPage - updateLoadingProgress: 17

**Parse error: ReferenceError: Can't find variable: $**

2015-03-15T22:40:02 [DEBUG] Network - Resource request error: 203 ( "Error downloading http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js - server replied: Not Found" ) URL: "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" 
2015-03-15T22:40:02 [DEBUG] WebPage - updateLoadingProgress: 100 
2015-03-15T22:40:02 [DEBUG] WebPage - setupFrame "" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - URI / 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Method POST 
2015-03-15T22:40:32 [DEBUG] HTTP Request - HTTP Version 1.1 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Query String  
2015-03-15T22:40:32 [DEBUG] HTTP Request - Receiving Header "Content-Length" = "1370" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Receiving Header "Content-Type" = "application/x-www-form-urlencoded" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Receiving Header "Host" = "127.0.0.1:8093" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Receiving Header "Connection" = "Keep-Alive" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Receiving Header "User-Agent" = "Apache-HttpClient/4.4 (Java 1.5 minimum; Java/1.8.0_25)" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Receiving Header "Accept-Encoding" = "gzip,deflate" 
2015-03-15T22:40:32 [DEBUG] HTTP Request - Method POST/PUT

**Comment by forced-request** [comment]
Thanks for the report! Before I start debugging I want to verify that the environment you're testing on is actually able to access the jquery libraries. I noticed in your example above (just under the parse error) that the server is throwing a 203 error when attempting to download the scripts.

**Comment by kulisu** [comment]
Hi @forced-request,

thanks for your quick reply first.
it's pretty weirded, and i've tried to replace [original resource](http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js) to [official link](https://code.jquery.com/jquery-1.10.2.min.js) but no luck.

Host OS: VMware ESXi 5.5 Update 2
Guest OS: Kali Linux 1.1.0 x64

Apache: 2.2.22
PHP: 5.4.36-0+deb7u3

```bash
# DNS testing
root@Kali:~/Desktop/Scripts# nslookup ajax.googleapis.com
Server:		192.168.30.2
Address:	192.168.30.2#53

Non-authoritative answer:
ajax.googleapis.com	canonical name = googleapis.l.google.com.
Name:	googleapis.l.google.com
Address: 74.125.23.95

# Connection testing
root@Kali:~/Desktop/Scripts# ping -c 1 ajax.googleapis.com
PING googleapis.l.google.com (74.125.23.95) 56(84) bytes of data.
64 bytes from tg-in-f95.1e100.net (74.125.23.95): icmp_req=1 ttl=46 time=9.74 ms

--- googleapis.l.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 9.743/9.743/9.743/0.000 ms

# Remote testing
root@Kali:~/Desktop/Scripts# curl -s "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"
/*! jQuery v1.10.2 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
//@ sourceMappingURL=jquery.min.map
*/
(function(e,t){var n,r,i=typeof t,o=e.location,a=e.document,s=a.documentElement,l=e.jQuery,u=e.$,c={},p=[],f="1.10.2",d=p.concat,h=p.push,g=
# .. SNIPP ..
.amd&&define("jquery",[],function(){return x}))})(window);

# Ooooooooooops :(
Received request with method type: POST
Processing Post Request
Beginning to parse page
	URL: http://192.168.30.56/resource-load.php?name=alert(299792458);
	Headers: GET /resource-load.php?name=alert(299792458); HTTP/1.1
Host: 192.168.30.56
Proxy-Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-TW,zh;q=0.8,en;q=0.6,zh-CN;q=0.4
Connection: close


Parse error: SyntaxError: Parse error
Parse error: ReferenceError: Can't find variable: $
```

**Comment by nvisium-shawn-smith** [comment]
Closed by request of @forced-request
