### ISSUE TITLE
burp intruder does not run

### ISSUE THREAD

**Issue by amolkedar** [nVisium/xssValidator#20]
I am following this article https://nvisium.com/blog/2014/01/31/accurate-xss-detection-with-burpsuite/
and have downloaded the jar file and phantomjs, but when i start the attack. no actions take place on the burpsuite. is there any place i can debug this?

**Comment by amolkedar** [comment]
well a little more writeup then my previous late night note....so i have burpsuite v 1.6.32 running on macbook pro and i am able to run intruder before installing the xssvalidator jar file. But once i install the jar file and i start the phantomjs instance the intruder does not run and is in a paused state

**Comment by nopnopnoppopopret** [comment]
I ran into the same issue, but don't have the time to debug the reason.  Use slimer.js instead.

**Comment by forced-request** [comment]
Take a look at the Burp extender output for xssValidator to see if there are any errors. I just tested and was unable to recreate the issue.

Which version of phantomjs are you using? I tested on 1.9.7

<img width="950" alt="screen shot 2016-02-28 at 9 02 49 pm" src="https://cloud.githubusercontent.com/assets/961246/13383975/a8d2d7e2-de5e-11e5-923a-25b86e8c8913.png">

**Comment by nopnopnoppopopret** [comment]
2.1 - latest

**Comment by forced-request** [comment]
Thank you. I can confirm that this is an issue with version 2 of Phantom.js. I'll work on a fix.

**Comment by chkaufmann** [comment]
Tried 2.1, still does not work. Tried 1.9.7 as well as John said he tested with that version, still same problem.
As soon as I close phantomjs, the intruder sends his requests
![capture](https://cloud.githubusercontent.com/assets/24633960/21293122/5613d8a4-c51b-11e6-847b-eef71759f4b7.JPG)

Wanted to try slimer instead but cant find slimer.ja anywhere! Has anyone a solution for me, I really would appreciate using this tool

**Comment by forced-request** [comment]
Sorry for the issues here. I haven't had much time to work on xssValidator lately. Hopefully in a few weeks I'll have a chance to dig in.

**Comment by gaurang8492** [comment]
Intruder isn't displaying anything when running xssValidator. I am using phantomjs version 1.9.7.
Any alternative to run this tool?

**Comment by forced-request** [comment]
Hey @gaurang8492 I'm not sure what issues others are having. I just tested with PhantomJS (2.1.1) and Burp Suite (1.7.16) and it seems to work fine for me. What are you seeing? 

@chkaufmann / @amolkedar sorry for bringing this back up -- did you ever get it working?

**Comment by amolkedar** [comment]
Let me try it again this week, i also upgraded my burp to 1.7.16, so will keep you posted on my findings

**Comment by amolkedar** [comment]
Hi @forced-request i just tried and my screen is pretty similar to @chkaufmann.... i cannot seem to get the burp to execute the attack, it seems to stuck at some

I can also confirm that phantomjs is listening on 127.0.0.1:8093

phantomjs 60462      xx   12u  IPv4 0xf542737a05eca973      0t0    TCP 127.0.0.1:8093 (LISTEN)




![screen shot 2017-01-24 at 2 40 24 pm](https://cloud.githubusercontent.com/assets/5334610/22263685/4691b546-e243-11e6-8b56-aa1ec89de4db.png)

![screen shot 2017-01-24 at 2 39 13 pm](https://cloud.githubusercontent.com/assets/5334610/22263826/c9949c74-e243-11e6-9598-a939ec19c627.png)

**Comment by amolkedar** [comment]
looking at the extender logs i can see a connection refused error

![screen shot 2017-01-24 at 3 42 29 pm](https://cloud.githubusercontent.com/assets/5334610/22265855/c53d1fea-e24b-11e6-9406-a0b119e7c6e0.png)

**Comment by ImBhargav** [comment]
@amolkedar  the issue your are facing is because XssValidator is not compatible with phantomjs v.2.0 and above. I too was having this issue, Then i downloaded Phantomjs v.1.9.7 and XssValidator v.1.1, And the problem was solved. And I'm sure this will work for you too.
[phantomjs-1.9.7.zip](https://github.com/nVisium/xssValidator/files/995679/phantomjs-1.9.7.zip)
[xss-validator-1.1.zip](https://github.com/nVisium/xssValidator/files/995686/xss-validator-1.1.zip)

**Comment by nvisium-shawn-smith** [comment]
Closed by request of @forced-request
