### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by PolarBearGod** [nVisium/xssValidator#21]
Seems like I am have such a simple issue that I cannot find the fix for. Following the README.md, downloaded Apache's HttpClient and HttpCore both to the target directory and extracted all *.jar files to the required directory `../xssValidator/burp-extender/lib`. I even moved the OSGi bundle to the targetted `lib` with no results. Currently `ant` and java version "1.7.0_91" installed.

After executing `ant`, I get a >BUILD FAILED message. 

> root@kali:~/Git/xssValidator/burp-extender/bin/burp# ant
> Buildfile: /root/Git/xssValidator/burp-extender/bin/burp/build.xml
> 
> compile:
>     [javac] /root/Git/xssValidator/burp-extender/bin/burp/build.xml:20: warning:                                             'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to                                             false for repeatable builds
>     [javac] Compiling 38 source files to /root/Git/xssValidator/burp-extender/bi                                            n
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:25:                                             error: package org.apache.commons.codec.binary does not exist
>     [javac] import org.apache.commons.codec.binary.Base64;
>     [javac]                                       ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:26:                                             error: package org.apache.http does not exist
>     [javac] import org.apache.http.HttpResponse;
>     [javac]                       ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:27:                                             error: package org.apache.http.client does not exist
>     [javac] import org.apache.http.client.HttpClient;
>     [javac]                              ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:28:                                             error: package org.apache.http.client.entity does not exist
>     [javac] import org.apache.http.client.entity.UrlEncodedFormEntity;
>     [javac]                                     ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:29:                                             error: package org.apache.http.client.methods does not exist
>     [javac] import org.apache.http.client.methods.HttpPost;
>     [javac]                                      ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:30:                                             error: package org.apache.http.impl.client does not exist
>     [javac] import org.apache.http.impl.client.HttpClientBuilder;
>     [javac]                                   ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:31:                                             error: package org.apache.http.message does not exist
>     [javac] import org.apache.http.message.BasicNameValuePair;
>     [javac]                               ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:32:                                             error: package org.apache.http.util does not exist
>     [javac] import org.apache.http.util.EntityUtils;
>     [javac]                            ^
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:44:                                             error: cannot find symbol
>     [javac]     private HttpClient            client;
>     [javac]             ^
>     [javac]   symbol:   class HttpClient
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:212:                                             error: cannot find symbol
>     [javac]         HttpPost detector = new HttpPost(detectorUrl);
>     [javac]         ^
>     [javac]   symbol:   class HttpPost
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:212:                                             error: cannot find symbol
>     [javac]         HttpPost detector = new HttpPost(detectorUrl);
>     [javac]                                 ^
>     [javac]   symbol:   class HttpPost
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:219:                                             error: cannot find symbol
>     [javac]                 byte[] encodedBytes = Base64.encodeBase64(messageInf                                            o
>     [javac]                                       ^
>     [javac]   symbol:   variable Base64
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:225:                                             error: cannot find symbol
>     [javac]                 byte[] encodedURLBytes = Base64.encodeBase64(intrude                                            rURL.getBytes());
>     [javac]                                          ^
>     [javac]   symbol:   variable Base64
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:229:                                             error: cannot find symbol
>     [javac]                 byte[] encodedHeaderBytes = Base64.encodeBase64(head                                            ers.getBytes());
>     [javac]                                             ^
>     [javac]   symbol:   variable Base64
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:233:                                             error: cannot find symbol
>     [javac]                 nameValuePairs.add(new BasicNameValuePair("http-resp                                            onse",
>     [javac]                                        ^
>     [javac]   symbol:   class BasicNameValuePair
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:235:                                             error: cannot find symbol
>     [javac]                 nameValuePairs.add(new BasicNameValuePair("http-url"                                            ,
>     [javac]                                        ^
>     [javac]   symbol:   class BasicNameValuePair
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:237:                                             error: cannot find symbol
>     [javac]                 nameValuePairs.add(new BasicNameValuePair("http-head                                            ers",
>     [javac]                                        ^
>     [javac]   symbol:   class BasicNameValuePair
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:241:                                             error: cannot find symbol
>     [javac]                 .setEntity(new UrlEncodedFormEntity(nameValuePairs))                                            ;
>     [javac]                                ^
>     [javac]   symbol:   class UrlEncodedFormEntity
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:243:                                             error: cannot find symbol
>     [javac]                 HttpResponse response = this.client.execute(detector                                            );
>     [javac]                 ^
>     [javac]   symbol:   class HttpResponse
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:244:                                             error: cannot find symbol
>     [javac]                 String responseAsString = EntityUtils.toString(respo                                            nse
>     [javac]                                           ^
>     [javac]   symbol:   variable EntityUtils
>     [javac]   location: class BurpExtender
>     [javac] /root/Git/xssValidator/burp-extender/src/burp/BurpExtender.java:360:                                             error: cannot find symbol
>     [javac]         this.client = HttpClientBuilder.create().build();
>     [javac]                       ^
>     [javac]   symbol:   variable HttpClientBuilder
>     [javac]   location: class BurpExtender
>     [javac] 21 errors
> 
> BUILD FAILED
> /root/Git/xssValidator/burp-extender/bin/burp/build.xml:20: Compile failed; see                                             the compiler error output for details.
> 
> Total time: 0 seconds

---

It feels like I have every *.jar file Apache has available. Any help would be appreciated.

**Comment by forced-request** [comment]
Hello, sorry for the delayed response here.

I wanted to confirm that you installed the apache packages into `/root/Git/xssValidator/burp-extender/lib`, which appears to be the proper path in your environment.

**Comment by iCynara** [comment]
I got exactly same errors, 
What i have downloaded httpcomponents-client-4.5.2-bin, httpcomponents-core-4.4.5

i certainly have all the jar in /xssValidator/burp-extender/lib

Is there anything else i need to do? Thanks a lot!

meow@meows-MacBook-Pro:~/Project/Burp/Tools/xssValidator/burp-extender/lib » ll
total 9376
-rw-r--r--@ 1 meow  staff    40K  1 May  2015 commons-cli-1.2.jar
-rw-r--r--@ 1 meow  staff   258K  1 May  2015 commons-codec-1.9.jar
-rw-r--r--@ 1 meow  staff    60K  1 May  2015 commons-logging-1.2.jar
-rw-r--r--@ 1 meow  staff    31K 21 Feb 16:07 fluent-hc-4.5.2.jar
-rw-r--r--@ 1 meow  staff   719K 21 Feb 16:05 httpclient-4.5.2.jar
-rw-r--r--@ 1 meow  staff   155K 21 Feb 16:07 httpclient-cache-4.5.2.jar
-rw-r--r--@ 1 meow  staff    17K 21 Feb 16:08 httpclient-win-4.5.2.jar
-rw-r--r--@ 1 meow  staff   319K 30 Dec  2015 httpcore-4.4.4.jar
-rw-r--r--@ 1 meow  staff   320K  8 Jun 12:39 httpcore-4.4.5.jar
-rw-r--r--@ 1 meow  staff    31K  8 Jun 12:41 httpcore-ab-4.4.5.jar
-rw-r--r--@ 1 meow  staff   348K  8 Jun 12:40 httpcore-nio-4.4.5.jar
-rw-r--r--@ 1 meow  staff    40K 21 Feb 16:06 httpmime-4.5.2.jar
-rw-r--r--@ 1 meow  staff   893K  1 May  2015 jna-4.1.0.jar
-rw-r--r--@ 1 meow  staff   1.4M  1 May  2015 jna-platform-4.1.0.jar

**Comment by iCynara** [comment]
Just going to answer my own question, Open build.xml under 
/xssValidator/burp-extender/bin/burp

That's what it is looking for exact. and older version of http component package can be found: 
https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore

	<path id="burp-extender.classpath">
        	<pathelement location="."/>
        	<pathelement location="../../lib/commons-codec-1.6.jar"/>
        	<pathelement location="../../lib/commons-logging-1.1.3.jar"/>
        	<pathelement location="../../lib/fluent-hc-4.3.6.jar"/>
        	<pathelement location="../../lib/httpclient-4.3.6.jar"/>
        	<pathelement location="../../lib/httpclient-cache-4.3.6.jar"/>
        	<pathelement location="../../lib/httpcore-4.3.3.jar"/>
        	<pathelement location="../../lib/httpmime-4.3.6.jar"/>
    	</path>

**Comment by rmbrown410** [comment]
@iCynara your a beast!  #problem_solved

**Comment by forced-request** [comment]
Sorry for not responding before, all. @iCynara is right: the build.xml is looking for specific, outdated versions of the components. You can download all of the libraries using the following commands:

```
mkdir ./burp-extender/lib
cd burp-extender/lib 
wget http://central.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
wget http://central.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
wget http://central.maven.org/maven2/org/apache/httpcomponents/fluent-hc/4.3.6/fluent-hc-4.3.6.jar
wget http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
wget http://central.maven.org/maven2/org/apache/httpcomponents/httpclient-cache/4.3.6/httpclient-cache-4.3.6.jar
wget http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
wget http://central.maven.org/maven2/org/apache/httpcomponents/httpmime/4.3.6/httpmime-4.3.6.jar
```
