### ISSUE TITLE
Unable to find slimer.js in the repository

### ISSUE THREAD

**Issue by techsethi** [nVisium/xssValidator#27]
Hi,

I was going through the video. https://www.youtube.com/watch?v=qS5PsxYY1uc 

I can find xss.js but am unable to find slimer.js.

Is slimer.js still relevant as video seems to be 2 year old ?

TIA

**Comment by forced-request** [comment]
As of right now we aren't supporting slimer.js, so it has been removed from the repository. Once they resolve this bug (https://github.com/laurentj/slimerjs/issues/284) we will begin to support slimer again. That being said, I haven't tested to see if the latest releases solve the problem mentioned there. 

You can find the old slimer.js file here: https://github.com/nVisium/xssValidator/blob/915d20969c20889d9a7b4d49c624a2253a1d228a/xss-detector/slimer.js

**Comment by techsethi** [comment]
Thanks for quick response. It worked perfectly with phantom.js. Amazing detection !!

I tried slimer.js as per your link.

Initially got:

./slimerjs --debug=true ../xssValidator/xss-detector/slimer.js
Error: Platform version '51.0.1' is not compatible with
minVersion >= 38.0.0
maxVersion <= 50.*
Gecko error: it seems /Applications/Firefox.app/Contents/MacOS/firefox is not compatible with SlimerJS.
See Gecko version compatibility. If version is correct, launch slimerjs
with --debug=true to see Firefox error message

but then after upping the version in slimer.js Maxversion to 51.*, the script runs but it doesn't work. Here are the errors being reported:

> JavaScript strict warning: coffee-scripts.js, line 8: SyntaxError: test for equality (==) mistyped as assignment (=)?

> JavaScript strict warning: file:///path/xssValidator/xss-detector/slimer.js, line 32: ReferenceError: assignment to undeclared variable parsePage
> JavaScript strict warning: file:///path/xssValidator/xss-detector/slimer.js, line 58: ReferenceError: assignment to undeclared variable reInitializeWebPage
> JavaScript strict warning: file:///path/xssValidator/xss-detector/slimer.js, line 60: ReferenceError: assignment to undeclared variable xss
> JavaScript strict warning: resource://gre/modules/ProfileAge.jsm, line 202: ReferenceError: reference to undefined property times.reset
> 

Anyways, xssValidator work perfect with phantom.js. Thanks again :-)
